version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
      - echo "Dependency installation completed"
  build:
    commands:
      - echo "Building Node.js application..."
      - npm run build || echo "No build script found, continuing..."
      - echo "Build completed successfully"
  post_build:
    commands:
      - echo "Build finished on `date`"
      - echo "Application ready for deployment"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .

cache:
  paths:
    - 'node_modules/**/*'
